# Generated by Django 5.2 on 2026-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=90)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
