# Generated by Django 5.2 on 2026-03-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
