# Generated by Django 5.2 on 2026-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=90)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
